### ISSUE TITLE
Server unable to start on Fabric 1.20.1

### ISSUE THREAD

**Issue by ArkoSammy12** [ArcaneWasTaken/LogIPRemover#2]
The server fails to start on the latest version of LogIPRemover for the 1.20.1 version of the game. Here is the full startup log

https://mclo.gs/7kG1yEw

It seems that the Fabric loader is unable to find the method signature "onPlayerConnect" which makes the mixin and the @Redirect tag fail.

**Comment by ArcaneWasTaken** [comment]
Fixed in d1596a4c9efd533ddb35638622bf70efd5440b82. Expect the new build on Modrinth soon.
